// Glossary — every method term in plain language, searchable, linked to lessons.
const GLOSSARY = [
  { id:"bip", cat:"Charting", term:"Basic Infertile Pattern (BIP)", lesson:"charting",
    def:"Your personal baseline on infertile days — consistently dry for some, habitual cell slough for others. Any change from it is your point of change. Established over your first 3 cycles." },
  { id:"peak", cat:"Mucus", term:"Peak Day", lesson:"mucus",
    def:"The last day of peak-quality mucus (clear, stretchy, wet, slippery). Identified the day after, when quality drops. Justisse counts 4 days after it." },
  { id:"poc", cat:"Charting", term:"Point of Change", lesson:"charting",
    def:"The first observation different from your BIP — the day your fertile window opens." },
  { id:"coverline", cat:"Temperature", term:"Coverline", lesson:"bbt",
    def:"A reference line you draw 0.05 °C above the highest of the six temperatures before your shift. Three temps above it — the third at least 0.1 °C higher — support confirming ovulation has passed." },
  { id:"slough", cat:"Mucus", term:"Cell slough", lesson:"mucus",
    def:"Pasty, crumbly, white-yellow discharge. Commonly confused with fertile mucus — if it's habitual and doesn't change with your cycle, it may be part of your BIP. Ask your practitioner." },
  { id:"doublecheck", cat:"Method", term:"The double-check", lesson:"bbt",
    def:"Justisse confirms ovulation only when both the Peak Day count and the temperature shift agree. Cross-checking is what makes symptothermal methods so effective." },
  { id:"hrhp", cat:"Method", term:"HRHP", lesson:"intro",
    def:"Holistic Reproductive Health Practitioner — a trained Justisse educator. Recommended, especially for pregnancy avoidance. Find one at justisse.ca." },
  { id:"luteal", cat:"Cycle", term:"Luteal phase", lesson:"bbt",
    def:"The days between ovulation and your next period, driven by progesterone — the reason your temperature stays high." },
  { id:"bbt", cat:"Temperature", term:"Basal body temperature (BBT)", lesson:"bbt",
    def:"Your resting temperature, taken before any activity. After ovulation, progesterone raises it by 0.2–0.5 °C — a rearview mirror that confirms, never predicts." },
  { id:"window", cat:"Charting", term:"Fertile window", lesson:"charting",
    def:"Opens at your point of change. Includes all days of observable mucus. Closes the evening of the 4th day after Peak, confirmed by your temperature shift." },
  { id:"cd1", cat:"Cycle", term:"Cycle Day 1", lesson:"charting",
    def:"The first day of full menstrual flow. Spotting before full flow doesn't count — CD 1 waits for a real flow day." },
  { id:"count", cat:"Charting", term:"The Peak + 4 count", lesson:"mucus",
    def:"After you identify Peak Day, count four full days. Justisse's count of 4 is one day more conservative than some methods — an extra margin of safety." },
  { id:"disturbed", cat:"Temperature", term:"Disturbed temperature", lesson:"bbt",
    def:"A reading distorted by illness, alcohol, broken sleep, or an unusual wake time. Mark it disturbed and leave it out when you read your shift." },
];
